### ISSUE TITLE
final project issues

### ISSUE THREAD

**Issue by benkeser** [amarra1122/FinalProject#3]
A couple issues to resolve:
1. There is no `report` directory in the repo, so the `docker run` mount command will fail. You need to add an empty folder to the repo to catch the report.
2. Please double check [the rubric](https://canvas.emory.edu/courses/104312/assignments/690911) to make sure your README complies with everything required. Some easy points out there.

I'll hold off on grading until after assignment deadline passes.

**Comment by amarra1122** [comment]
Thank you very much for the pointers - my apologies. All should be fixed now!
